# Generated by Django 5.2.17 on 2026-08-18 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPredictivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('deporte', models.CharField(max_length=80)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('fecha_calibracion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='ranking',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('moneyline', 'Resultado / moneyline'), ('totales', 'Totales over-under'), ('handicap', 'Handicap'), ('anotadores', 'Anotadores')], max_length=40)),
                ('es_premium', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='ventas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidades', models.JSONField()),
                ('valor_esperado', models.FloatField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('version_modelo', models.CharField(max_length=40)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='ventas.mercado')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='ventas.modelopredictivo')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('renovacion_auto', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
